package view;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFormattedTextField;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JSeparator;
import javax.swing.JTable;
import model.Utilities;

public class ConsultaJogos extends javax.swing.JFrame {
    private Utilities utilities = new Utilities();
    
    public ConsultaJogos() {
        initComponents();
        
        utilities.centralizarFrame(this);
        setIconImage(utilities.adicionarIcone("/src/images/BuscarJogo.png"));
    }

    public Utilities getUtilities() {
        return utilities;
    }

    public JButton getjButtonAvaliar() {
        return jButtonAvaliar;
    }

    public JButton getjButtonImagens() {
        return jButtonImagens;
    }

    public JButton getjButtonIniciarBusca() {
        return jButtonIniciarBusca;
    }

    public JButton getjButtonSair() {
        return jButtonSair;
    }

    public JButton getjButtonVerificarDisponibilidade() {
        return jButtonVerificarDisponibilidade;
    }

    public JComboBox getjComboBoxDeposito() {
        return jComboBoxDeposito;
    }

    public JComboBox getjComboBoxDistribuidora() {
        return jComboBoxDistribuidora;
    }

    public JComboBox getjComboBoxFaixaEtaria() {
        return jComboBoxFaixaEtaria;
    }

    public JComboBox getjComboBoxGenero() {
        return jComboBoxGenero;
    }

    public JFormattedTextField getjFormattedTextFieldVlFinal() {
        return jFormattedTextFieldVlFinal;
    }

    public JFormattedTextField getjFormattedTextFieldVlInicial() {
        return jFormattedTextFieldVlInicial;
    }

    public JLabel getjLabelDeposito() {
        return jLabelDeposito;
    }

    public JLabel getjLabelDistribuidora() {
        return jLabelDistribuidora;
    }

    public JLabel getjLabelFaixaEtaria() {
        return jLabelFaixaEtaria;
    }

    public JLabel getjLabelGenero() {
        return jLabelGenero;
    }

    public JLabel getjLabelOpcoesConsulta() {
        return jLabelOpcoesConsulta;
    }

    public JLabel getjLabelVlFinal() {
        return jLabelVlFinal;
    }

    public JLabel getjLabelVlInicial() {
        return jLabelVlInicial;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public JSeparator getjSeparator1() {
        return jSeparator1;
    }

    public JSeparator getjSeparator2() {
        return jSeparator2;
    }

    public JTable getjTableListaJogos() {
        return jTableListaJogos;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelOpcoesConsulta = new javax.swing.JLabel();
        jLabelDistribuidora = new javax.swing.JLabel();
        jComboBoxDistribuidora = new javax.swing.JComboBox();
        jSeparator1 = new javax.swing.JSeparator();
        jLabelGenero = new javax.swing.JLabel();
        jComboBoxGenero = new javax.swing.JComboBox();
        jLabelFaixaEtaria = new javax.swing.JLabel();
        jComboBoxFaixaEtaria = new javax.swing.JComboBox();
        jLabelDeposito = new javax.swing.JLabel();
        jComboBoxDeposito = new javax.swing.JComboBox();
        jLabelVlInicial = new javax.swing.JLabel();
        jLabelVlFinal = new javax.swing.JLabel();
        jFormattedTextFieldVlInicial = new javax.swing.JFormattedTextField();
        jFormattedTextFieldVlFinal = new javax.swing.JFormattedTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableListaJogos = new javax.swing.JTable();
        jButtonImagens = new javax.swing.JButton();
        jButtonAvaliar = new javax.swing.JButton();
        jButtonVerificarDisponibilidade = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();
        jButtonIniciarBusca = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Busca de Jogos");

        jLabelOpcoesConsulta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelOpcoesConsulta.setText("Opções de busca:");

        jLabelDistribuidora.setText("Distribuidora:");

        jLabelGenero.setText("Gênero:");

        jLabelFaixaEtaria.setText("Faixa Etária:");

        jLabelDeposito.setText("Depósito:");

        jLabelVlInicial.setText("Valor Inicial:");

        jLabelVlFinal.setText("Valor Final:");

        jFormattedTextFieldVlInicial.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("###0.###"))));

        jFormattedTextFieldVlFinal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("###0.###"))));

        jTableListaJogos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nome", "Distribuidora", "Gênero", "Faixa Etária", "Valor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableListaJogos);
        if (jTableListaJogos.getColumnModel().getColumnCount() > 0) {
            jTableListaJogos.getColumnModel().getColumn(0).setPreferredWidth(2);
            jTableListaJogos.getColumnModel().getColumn(1).setPreferredWidth(300);
        }

        jButtonImagens.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Escolher.png"))); // NOI18N
        jButtonImagens.setText("Imagens");

        jButtonAvaliar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Avaliar.png"))); // NOI18N
        jButtonAvaliar.setText("Avaliar");

        jButtonVerificarDisponibilidade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ProdEstoque.png"))); // NOI18N
        jButtonVerificarDisponibilidade.setText("Verificar Disponibilidade");

        jButtonSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Sair.png"))); // NOI18N
        jButtonSair.setText("Sair");
        jButtonSair.setToolTipText("");

        jButtonIniciarBusca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Pesquisar.png"))); // NOI18N
        jButtonIniciarBusca.setText("Iniciar busca");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(jSeparator2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 782, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonImagens)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAvaliar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonVerificarDisponibilidade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonSair))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelOpcoesConsulta)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelGenero)
                                    .addComponent(jLabelDistribuidora))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jComboBoxDistribuidora, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBoxGenero, 0, 149, Short.MAX_VALUE))
                                .addGap(59, 59, 59)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelFaixaEtaria)
                                    .addComponent(jLabelDeposito))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jComboBoxFaixaEtaria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBoxDeposito, 0, 145, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelVlInicial)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jFormattedTextFieldVlInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jLabelVlFinal)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jFormattedTextFieldVlFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButtonIniciarBusca)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelOpcoesConsulta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDistribuidora)
                    .addComponent(jComboBoxDistribuidora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFaixaEtaria)
                    .addComponent(jComboBoxFaixaEtaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelVlInicial)
                    .addComponent(jFormattedTextFieldVlInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelVlFinal)
                        .addComponent(jFormattedTextFieldVlFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonIniciarBusca))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelGenero)
                        .addComponent(jComboBoxGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelDeposito)
                        .addComponent(jComboBoxDeposito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonImagens)
                    .addComponent(jButtonAvaliar)
                    .addComponent(jButtonVerificarDisponibilidade)
                    .addComponent(jButtonSair))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAvaliar;
    private javax.swing.JButton jButtonImagens;
    private javax.swing.JButton jButtonIniciarBusca;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JButton jButtonVerificarDisponibilidade;
    private javax.swing.JComboBox jComboBoxDeposito;
    private javax.swing.JComboBox jComboBoxDistribuidora;
    private javax.swing.JComboBox jComboBoxFaixaEtaria;
    private javax.swing.JComboBox jComboBoxGenero;
    private javax.swing.JFormattedTextField jFormattedTextFieldVlFinal;
    private javax.swing.JFormattedTextField jFormattedTextFieldVlInicial;
    private javax.swing.JLabel jLabelDeposito;
    private javax.swing.JLabel jLabelDistribuidora;
    private javax.swing.JLabel jLabelFaixaEtaria;
    private javax.swing.JLabel jLabelGenero;
    private javax.swing.JLabel jLabelOpcoesConsulta;
    private javax.swing.JLabel jLabelVlFinal;
    private javax.swing.JLabel jLabelVlInicial;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTableListaJogos;
    // End of variables declaration//GEN-END:variables
}
