/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;

/**
 *
 * @author eduardo.151294
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
    }

    public JMenuBar getjMenuBar1() {
        return jMenuBar1;
    }

    public JMenu getjMenuCadastros() {
        return jMenuCadastros;
    }

    public JMenu getjMenuConsultas() {
        return jMenuConsultas;
    }

    public JMenuItem getjMenuItemDistribuidoras() {
        return jMenuItemDistribuidoras;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuCadastros = new javax.swing.JMenu();
        jMenuItemDistribuidoras = new javax.swing.JMenuItem();
        jMenuConsultas = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EGames - Menu Principal");
        setExtendedState(MAXIMIZED_BOTH);
        setIconImages(null);
        setName("menuPrincipal");

        jMenuCadastros.setText("Cadastros");

        jMenuItemDistribuidoras.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemDistribuidoras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Distribuidoras.png"))); // NOI18N
        jMenuItemDistribuidoras.setText("Distribuidoras");
        jMenuCadastros.add(jMenuItemDistribuidoras);

        jMenuBar1.add(jMenuCadastros);

        jMenuConsultas.setText("Consultas");
        jMenuBar1.add(jMenuConsultas);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCadastros;
    private javax.swing.JMenu jMenuConsultas;
    private javax.swing.JMenuItem jMenuItemDistribuidoras;
    // End of variables declaration//GEN-END:variables
}
