package view;

import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JPopupMenu;
import javax.swing.JSeparator;
import model.Utilities;

public class MenuPrincipal extends javax.swing.JFrame {
    private Utilities utilities = new Utilities();
    
    public MenuPrincipal() {
        initComponents();
        setIconImage(utilities.adicionarIcone("/src/images/Menu.png"));
    }

    public JMenuBar getjMenuBar1() {
        return jMenuBarPrincipal;
    }

    public JMenu getjMenuCadastros() {
        return jMenuCadastros;
    }

    public JMenu getjMenuConsultas() {
        return jMenuConsultas;
    }

    public JMenuItem getjMenuItemDistribuidoras() {
        return jMenuItemDistribuidoras;
    }

    public JMenuItem getjMenuItemGeneros() {
        return jMenuItemGeneros;
    }

    public JMenuItem getjMenuItemFaixasEtarias() {
        return jMenuItemFaixasEtarias;
    }

    public JMenuItem getjMenuItemDepositos() {
        return jMenuItemDepositos;
    }

    public JPopupMenu.Separator getjSeparator1() {
        return jSeparator1;
    }

    public JPopupMenu.Separator getjSeparator2() {
        return jSeparator2;
    }

    public JSeparator getjSeparator3() {
        return jSeparator3;
    }

    public JMenuBar getjMenuBar2() {
        return jMenuBar2;
    }

    public JMenu getjMenuEstoque() {
        return jMenuEstoque;
    }

    public JMenu getjMenu1() {
        return jMenu1;
    }

    public JMenu getjMenu2() {
        return jMenu2;
    }

    public JMenu getjMenu3() {
        return jMenu3;
    }

    public JMenuBar getjMenuBarPrincipal() {
        return jMenuBarPrincipal;
    }

    public JMenuItem getjMenuItemJogos() {
        return jMenuItemJogos;
    }

    public JLabel getjLabelBackground() {
        return jLabelBackground;
    }

    public JMenuItem getjMenuItem1() {
        return jMenuItem1;
    }

    public JMenuItem getjMenuItemBuscaJogos() {
        return jMenuItemBuscaJogos;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jLabelBackground = new javax.swing.JLabel();
        jMenuBarPrincipal = new javax.swing.JMenuBar();
        jMenuCadastros = new javax.swing.JMenu();
        jMenuItemDistribuidoras = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItemGeneros = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItemFaixasEtarias = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItemJogos = new javax.swing.JMenuItem();
        jMenuEstoque = new javax.swing.JMenu();
        jMenuItemDepositos = new javax.swing.JMenuItem();
        jMenuConsultas = new javax.swing.JMenu();
        jMenuItemBuscaJogos = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenu2.setText("File");
        jMenuBar2.add(jMenu2);

        jMenu3.setText("Edit");
        jMenuBar2.add(jMenu3);

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EGames - Menu Principal");
        setExtendedState(MAXIMIZED_BOTH);
        setIconImages(null);
        setName("menuPrincipal"); // NOI18N

        jLabelBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Background.png"))); // NOI18N

        jMenuCadastros.setText("Jogos");

        jMenuItemDistribuidoras.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemDistribuidoras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Distribuidoras.png"))); // NOI18N
        jMenuItemDistribuidoras.setText("Distribuidoras");
        jMenuCadastros.add(jMenuItemDistribuidoras);
        jMenuCadastros.add(jSeparator1);

        jMenuItemGeneros.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemGeneros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Genero.png"))); // NOI18N
        jMenuItemGeneros.setText("Gêneros");
        jMenuCadastros.add(jMenuItemGeneros);
        jMenuCadastros.add(jSeparator2);

        jMenuItemFaixasEtarias.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemFaixasEtarias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/FaixaEtaria.png"))); // NOI18N
        jMenuItemFaixasEtarias.setText("Faixas Etárias");
        jMenuCadastros.add(jMenuItemFaixasEtarias);
        jMenuCadastros.add(jSeparator3);

        jMenuItemJogos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_J, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemJogos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Jogos.png"))); // NOI18N
        jMenuItemJogos.setText("Jogos");
        jMenuCadastros.add(jMenuItemJogos);

        jMenuBarPrincipal.add(jMenuCadastros);

        jMenuEstoque.setText("Estoque");

        jMenuItemDepositos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemDepositos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Depositos.png"))); // NOI18N
        jMenuItemDepositos.setText("Depósitos");
        jMenuEstoque.add(jMenuItemDepositos);

        jMenuBarPrincipal.add(jMenuEstoque);

        jMenuConsultas.setText("Consultas");

        jMenuItemBuscaJogos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_J, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemBuscaJogos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BuscarJogo.png"))); // NOI18N
        jMenuItemBuscaJogos.setText("Buscar Jogos");
        jMenuConsultas.add(jMenuItemBuscaJogos);

        jMenuBarPrincipal.add(jMenuConsultas);

        setJMenuBar(jMenuBarPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabelBackground, javax.swing.GroupLayout.PREFERRED_SIZE, 1080, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 109, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelBackground;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBarPrincipal;
    private javax.swing.JMenu jMenuCadastros;
    private javax.swing.JMenu jMenuConsultas;
    private javax.swing.JMenu jMenuEstoque;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItemBuscaJogos;
    private javax.swing.JMenuItem jMenuItemDepositos;
    private javax.swing.JMenuItem jMenuItemDistribuidoras;
    private javax.swing.JMenuItem jMenuItemFaixasEtarias;
    private javax.swing.JMenuItem jMenuItemGeneros;
    private javax.swing.JMenuItem jMenuItemJogos;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
